#!/bin/bash

SESSION_NAME=galaxywinds
ENV=galaxywinds
PROJECT_PATH='~/Projects/galaxywinds'

source ~/miniconda3/etc/profile.d/conda.sh

tmux has-session -t $SESSION_NAME 2>/dev/null

if [ $? != 0 ]
then
    tmux new-session -s $SESSION_NAME -n editor -d
    tmux send-keys -t $SESSION_NAME "cd $PROJECT_PATH" C-m
    tmux send-keys -t $SESSION_NAME "conda activate $ENV" C-m
    tmux send-keys -t $SESSION_NAME "clear" C-m
    tmux send-keys -t $SESSION_NAME "$EDITOR" C-m
    tmux new-window -n console -t $SESSION_NAME -d
    tmux send-keys -t $SESSION_NAME:1 "cd $PROJECT_PATH" C-m
    tmux send-keys -t $SESSION_NAME:1 "conda activate $ENV" C-m
    tmux send-keys -t $SESSION_NAME:1 "clear" C-m
#    tmux new-window -n notebook -t $SESSION_NAME -d
#    tmux send-keys -t $SESSION_NAME:2 "cd $PROJECT_PATH/Notebooks" C-m
#    tmux send-keys -t $SESSION_NAME:2 "conda activate $ENV" C-m
#    tmux send-keys -t $SESSION_NAME:2 "clear" C-m
fi

tmux attach -t $SESSION_NAME:0
