#!/bin/zsh

open -g "https://www.overleaf.com/project" 
open -g "https://www.mendeley.com/reference-manager/library/all-references/" 
open -g "https://education.github.com/git-cheat-sheet-education.pdf" 
open -g "https://docs.conda.io/projects/conda/en/4.6.0/_downloads/52a95608c49671267e40c689e0bc00ca/conda-cheatsheet.pdf" 
open -g "https://github.com/michaeljennings11" 
